[package]
name = "weevy-camo-wasm"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
description = "A powerful rewriter"

[dependencies]
wasm-bindgen = "0.2.100"
weevy-camo = { version = "0.1.0", path = "../weevy-camo" }

[lib]
crate-type = ["cdylib", "rlib"]